import DocsLayout from "../../../components/Docs/DocsLayout";
import {
  Bullets,
  DocLink,
  ExternalLink,
  Fields,
  P,
  PageTitle,
  Section,
} from "../../../components/Docs/elements";

const Exploration = () => (
  <DocsLayout
    href="/documentation/tutorial/exploration"
    title="Paper Exploration"
    description="How to search Qresp servers and explore the charts, datasets, scripts, tools and workflows of a curated paper."
  >
    <PageTitle eyebrow="Tutorial · Step 4" title="Paper Exploration">
      The <DocLink href="/explorer">Qresp Explorer</DocLink> is a GUI to explore
      and make available data on a per-publication basis. It provides a portal
      for the scientific community to access datasets, tools and workflows of a
      published scientific paper, enabling the reproducibility and validation
      of the paper results.
    </PageTitle>

    <Section title="Access a Qresp server instance">
      <P>
        This step allows the user to choose one or all Qresp instances to
        explore the curated papers. See the{" "}
        <DocLink href="/documentation/curation-and-exploration#the-qresp-ecosystem">
          Qresp ecosystem
        </DocLink>{" "}
        for the list of active nodes.
      </P>
    </Section>

    <Section title="Search and filtered search">
      <P>
        This step allows the user to filter their search results by entering
        any of the following:
      </P>
      <Bullets
        items={[
          "General keyword search",
          "Collection names",
          "DOI of the paper",
          "Tags of the paper",
          "Title of the paper",
          "Authors of the paper",
          "Publication source",
        ]}
      />
      <P>
        Alternatively, the user can click the search button to view all papers
        without applying any filter.
      </P>
    </Section>

    <Section title="View paper information">
      <P>
        This step allows the user to view and download the files that generated
        each figure or table, and the paper&rsquo;s datasets, scripts, tools and
        workflow.
      </P>
      <P>
        Explorers also have extra features when viewing a chart, shown beside
        it:
      </P>
      <Fields
        items={[
          [
            "Data Tree",
            "Shows all the files in a tree format, i.e. it redirects the user to the source of the data.",
          ],
          [
            "Workflow",
            "Shows the workflow which represents how the figure or table was created: a subgraph of the entire workflow generated by the curator, keeping only the nodes that were involved in the creation of the chart.",
          ],
          [
            "Download",
            "Redirects the user to Globus (if available) to download the entire paper content using GridFTP.",
          ],
          [
            "Notebook",
            <span key="nb">
              Redirects the user to the notebook file provided by the curator to
              create this chart, if available, previewed using{" "}
              <ExternalLink href="https://nbviewer.org/">nbviewer</ExternalLink>.
            </span>,
          ],
        ]}
      />
    </Section>
  </DocsLayout>
);

export default Exploration;
