import PropTypes from "prop-types";

import { Box, Tooltip, Typography } from "@mui/material";
import { East } from "@mui/icons-material";

import { KIND_STYLE } from "./Types";

const ORDER = ["EXTERNAL", "DATASET", "TOOL", "SCRIPT", "CHART"];

const INFO = {
  EXTERNAL: "Content used in the paper but not generated by it, such as a public database entry.",
  DATASET: "Data used or produced in the work.",
  TOOL: "Software or an experimental set-up used in the work.",
  SCRIPT: "The curator's own code: analysis, post-processing or plotting.",
  CHART: "A figure or table in the paper. Workflows usually end here.",
};

// One row above the drawing, in the same colours and shapes the boxes use.
// `direction` is accepted for older callers; the legend is always a row now.
// eslint-disable-next-line no-unused-vars
const Legend = ({ direction }) => (
  <Box
    data-testid="workflow-legend"
    sx={{ display: "flex", flexWrap: "wrap", alignItems: "center", gap: 1.5, mb: 1 }}
  >
    {ORDER.map((kind) => {
      const style = KIND_STYLE[kind];
      return (
        <Tooltip key={kind} title={INFO[kind]} arrow describeChild>
          <Box sx={{ display: "flex", alignItems: "center", gap: 0.75, cursor: "help" }}>
            <Box
              aria-hidden="true"
              sx={{
                width: 18,
                height: 12,
                borderRadius: "3px",
                bgcolor: style.fill,
                border: `1.5px solid ${style.accent}`,
              }}
            />
            <Typography variant="caption" sx={{ color: "text.secondary", fontWeight: 500 }}>
              {style.name}
            </Typography>
          </Box>
        </Tooltip>
      );
    })}
    <Box sx={{ display: "flex", alignItems: "center", gap: 0.5, ml: { sm: "auto" } }}>
      <East sx={{ fontSize: 16, color: "#9AA7B0" }} aria-hidden="true" />
      <Typography variant="caption" color="text.secondary">
        Arrows point the way the work flows. Hover a box to trace it.
      </Typography>
    </Box>
  </Box>
);

Legend.propTypes = {
  direction: PropTypes.string,
};

export default Legend;
