import { Fragment } from "react";
import PropTypes from "prop-types";

import { Box, Typography } from "@mui/material";

import { displayUrl, externalLabel } from "../../Utils/externalData";
import {
  CHART,
  CONSUMES,
  EXTERNAL,
  FEEDS_INTO,
  RELATED_TO,
  GENERATES,
  USES_TOOL,
  fromStoredEdge,
  prefixOf,
} from "../../Utils/workflowGraph";

// The workflow, in words, for a reader.
//
// The graph below this is a picture: good for seeing shape, poor for reading
// on a phone and impossible to read with a screen reader. This says the same
// thing as a short list of sentences, which is what most readers of a
// published record actually want -- "this figure came from that script, which
// used this data".
//
// READ-ONLY, and structurally so: it takes the saved graph and renders it.
// There is no edit affordance here at all, because the place to change a
// workflow is the Curator.
//
// It is organised BY FIGURE because that is the question a reader arrives
// with. A resource that feeds nothing still appears, at the end, rather than
// being dropped -- a dataset nobody wired up is still part of the record.

const SECTION_BY_PREFIX = {
  c: "charts",
  d: "datasets",
  s: "scripts",
  t: "tools",
};

// How each relationship reads in a sentence. The stored type is a code; this
// is the only place it becomes English, so the two cannot drift.
const RELATION_TEXT = {
  [CONSUMES]: "uses",
  [USES_TOOL]: "uses tool",
  [GENERATES]: "generated by",
  // Read from the downstream script's side, which is where this list stands.
  [FEEDS_INTO]: "feeds into",
  // No direction: this one says only that the two belong together, so it is
  // worded the same whichever end the reader is standing on.
  [RELATED_TO]: "related to",
};

const labelOf = (artifact, id) => {
  if (prefixOf(id) === EXTERNAL) return externalLabel(artifact, id);
  const named =
    (artifact &&
      (artifact.caption ||
        artifact.packageName ||
        artifact.programName ||
        artifact.facilityName ||
        artifact.readme)) ||
    "";
  const trimmed = String(named).replace(/\s+/g, " ").trim();
  if (!trimmed) return id;
  return trimmed.length > 70 ? `${trimmed.slice(0, 69)}…` : trimmed;
};

/**
 * A node, linked to the section that already shows it in full.
 *
 * Local artifacts link to their own section on this page -- the Drawer gives
 * each one an id from its heading -- so a reader can go from "generated by
 * plot.py" to the script itself. External data links OUT, and only when the
 * stored value is an http(s) URL: see `displayUrl`.
 */
const NodeLabel = ({ artifact, id }) => {
  const text = labelOf(artifact, id);
  if (prefixOf(id) === EXTERNAL) {
    const href = displayUrl(artifact);
    return (
      <Fragment>
        {href ? (
          <a href={href} target="_blank" rel="noopener noreferrer">
            {text}
          </a>
        ) : (
          <span>{text}</span>
        )}{" "}
        <Typography variant="caption" component="span" color="text.secondary">
          (external)
        </Typography>
      </Fragment>
    );
  }
  const section = SECTION_BY_PREFIX[prefixOf(id)];
  return section ? <a href={`#${section}`}>{text}</a> : <span>{text}</span>;
};

const WorkflowSummary = ({ workflow, charts, datasets, scripts, tools, external }) => {
  const byId = {};
  [charts, datasets, scripts, tools, external].forEach((list) =>
    (list || []).forEach((item) => {
      if (item && item.id) byId[item.id] = item;
    })
  );

  const edges = ((workflow || {}).edges || [])
    .map(fromStoredEdge)
    .filter((edge) => edge.from && edge.to);
  if (!edges.length) return null;

  // What points AT each node, which is how a figure's story is assembled.
  const incoming = {};
  edges.forEach((edge) => {
    (incoming[edge.to] = incoming[edge.to] || []).push(edge);
  });

  const chartIds = Object.keys(byId).filter((id) => prefixOf(id) === CHART);
  const figures = chartIds.filter((id) => (incoming[id] || []).length);

  // Everything that is in the graph but is not part of a figure's story.
  const accountedFor = new Set();
  const walk = (id, depth = 0) => {
    if (depth > 12 || accountedFor.has(id)) return;   // the graph is acyclic
    accountedFor.add(id);
    (incoming[id] || []).forEach((edge) => walk(edge.from, depth + 1));
  };
  figures.forEach((id) => walk(id));
  const elsewhere = edges
    .flatMap((edge) => [edge.from, edge.to])
    .filter((id) => !accountedFor.has(id));

  /** One node and, beneath it, whatever fed it. */
  const Branch = ({ id, depth }) => (
    <Box
      component="li"
      sx={{ mt: 0.25, minWidth: 0 }}
      data-testid={`workflow-summary-node-${id}`}
    >
      <Typography variant="body2" component="span" sx={{ overflowWrap: "anywhere" }}>
        <NodeLabel artifact={byId[id]} id={id} />
      </Typography>
      {(incoming[id] || []).length ? (
        <Box component="ul" sx={{ m: 0, pl: 2.5, listStyle: "none" }}>
          {(incoming[id] || []).map((edge) => (
            <Fragment key={`${edge.from}-${edge.to}-${edge.type}`}>
              <Box component="li" sx={{ minWidth: 0 }}>
                <Typography
                  variant="caption"
                  color="text.secondary"
                  component="span"
                >
                  {/* An untyped legacy edge says only that the two are
                      connected, which is all the record actually claims. */}
                  {RELATION_TEXT[edge.type] || "connected to"}:{" "}
                </Typography>
                <Typography variant="body2" component="span" sx={{ overflowWrap: "anywhere" }}>
                  <NodeLabel artifact={byId[edge.from]} id={edge.from} />
                </Typography>
                {depth < 3 && (incoming[edge.from] || []).length ? (
                  <Box component="ul" sx={{ m: 0, pl: 2.5, listStyle: "none" }}>
                    <Branch id={edge.from} depth={depth + 1} />
                  </Box>
                ) : null}
              </Box>
            </Fragment>
          ))}
        </Box>
      ) : null}
    </Box>
  );

  return (
    <Box sx={{ mb: 2, minWidth: 0 }} data-testid="workflow-summary">
      <Box component="ul" sx={{ m: 0, p: 0, listStyle: "none" }}>
        {figures.map((id) => (
          <Box
            component="li"
            key={id}
            sx={{ mb: 1.5, minWidth: 0 }}
            data-testid={`workflow-summary-figure-${id}`}
          >
            <Typography variant="subtitle2" sx={{ overflowWrap: "anywhere" }}>
              <NodeLabel artifact={byId[id]} id={id} />
            </Typography>
            <Box component="ul" sx={{ m: 0, pl: 2, listStyle: "none" }}>
              {(incoming[id] || []).map((edge) => (
                <Box
                  component="li"
                  key={`${edge.from}-${edge.to}-${edge.type}`}
                  sx={{ minWidth: 0 }}
                  data-testid={`workflow-summary-edge-${edge.from}-${edge.to}`}
                >
                  <Typography variant="caption" color="text.secondary" component="span">
                    {RELATION_TEXT[edge.type] || "connected to"}:{" "}
                  </Typography>
                  <Typography variant="body2" component="span" sx={{ overflowWrap: "anywhere" }}>
                    <NodeLabel artifact={byId[edge.from]} id={edge.from} />
                  </Typography>
                  {(incoming[edge.from] || []).length ? (
                    <Box component="ul" sx={{ m: 0, pl: 2.5, listStyle: "none" }}>
                      {(incoming[edge.from] || []).map((inner) => (
                        <Box
                          component="li"
                          key={`${inner.from}-${inner.to}-${inner.type}`}
                          sx={{ minWidth: 0 }}
                          data-testid={`workflow-summary-edge-${inner.from}-${inner.to}`}
                        >
                          <Typography variant="caption" color="text.secondary" component="span">
                            {RELATION_TEXT[inner.type] || "connected to"}:{" "}
                          </Typography>
                          <Typography variant="body2" component="span" sx={{ overflowWrap: "anywhere" }}>
                            <NodeLabel artifact={byId[inner.from]} id={inner.from} />
                          </Typography>
                        </Box>
                      ))}
                    </Box>
                  ) : null}
                </Box>
              ))}
            </Box>
          </Box>
        ))}
      </Box>

      {/* Connected to something, but not to any figure. Still part of the
          record, so still shown rather than quietly dropped. */}
      {elsewhere.length ? (
        <Box sx={{ mt: 1 }} data-testid="workflow-summary-other">
          <Typography variant="caption" color="text.secondary" display="block">
            Also in this workflow
          </Typography>
          <Typography variant="body2" sx={{ overflowWrap: "anywhere" }}>
            {Array.from(new Set(elsewhere)).map((id, index) => (
              <Fragment key={id}>
                {index ? ", " : ""}
                <NodeLabel artifact={byId[id]} id={id} />
              </Fragment>
            ))}
          </Typography>
        </Box>
      ) : null}
    </Box>
  );
};

WorkflowSummary.propTypes = {
  workflow: PropTypes.object,
};

export default WorkflowSummary;
