import { Box, Link as MuiLink } from "@mui/material";

import DocsLayout from "../../components/Docs/DocsLayout";
import {
  Callout,
  DataTable,
  DocLink,
  ExternalLink,
  P,
  PageTitle,
  Section,
} from "../../components/Docs/elements";

const RELEASES = [
  {
    name: "Qresp",
    page: "/documentation/installation/qresp",
    version: "v2.0.5",
    archive: "https://github.com/qresp-code-development/qresp/archive/v2.0.5.tar.gz",
    label: "qresp:latest",
  },
  {
    name: "Qresp Organizer",
    page: "/documentation/installation/qresp-organizer",
    version: "v1.1.0",
    archive: "https://github.com/qresp-code-development/qresp-organizer/archive/v1.1.0.tar.gz",
    label: "organizer:latest",
  },
];

// The schema files exactly as the Qresp project published them, served from
// this site's /schema/ folder.
export const SCHEMAS = [
  { date: "Oct 19, 2020", version: "1.2" },
  { date: "Sep 20, 2019", version: "1.1" },
  { date: "Dec 18, 2018", version: "1.0" },
];

const Download = () => (
  <DocsLayout
    href="/documentation/download"
    title="Download"
    description="Download Qresp and the Qresp Organizer, and every published version of the Qresp metadata JSON schema."
  >
    <PageTitle eyebrow="Getting started" title="Download">
      Qresp is an integrated suite of two software applications.
    </PageTitle>

    <Section title="Applications">
      <DataTable
        caption="Qresp applications"
        columns={["Application", "Version", "Download"]}
        rows={RELEASES.map((release) => [
          <DocLink key="p" href={release.page} sx={{ fontWeight: 600 }}>
            {release.name}
          </DocLink>,
          release.version,
          <ExternalLink key="a" href={release.archive}>{release.label}</ExternalLink>,
        ])}
      />
      <Callout kind="tip">
        You can view, fork, and contribute to the open source Qresp on the{" "}
        <ExternalLink href="https://github.com/qresp-code-development/qresp">
          Qresp GitHub repository
        </ExternalLink>
        .
      </Callout>
    </Section>

    <Section title="Metadata schema">
      <P>
        The metadata file generated by the Curator is encoded using the{" "}
        <ExternalLink href="https://www.json.org/">JSON</ExternalLink>{" "}
        (JavaScript Object Notation) syntax. A{" "}
        <ExternalLink href="https://json-schema.org/">JSON schema</ExternalLink>{" "}
        is used to validate the metadata file.
      </P>
      <P>List of schema versions:</P>
      <DataTable
        caption="Schema versions"
        columns={["Release date", "Version (click to download)"]}
        rows={SCHEMAS.map(({ date, version }) => [
          date,
          <Box key={version} component="span">
            <MuiLink
              href={`/schema/v${version}.json`}
              download={`qresp-schema-v${version}.json`}
              underline="hover"
              sx={{ fontWeight: 600 }}
            >
              {version}
            </MuiLink>
          </Box>,
        ])}
      />
    </Section>
  </DocsLayout>
);

export default Download;
